name: device_calendar_example
description: Demonstrates how to use the device_calendar plugin.
version: 3.2.0
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.3
  uuid: ^4.6.0
  flutter_timezone: ^5.1.0
  device_calendar:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true