name: device_calendar_example
description: Demonstrates how to use the device_calendar plugin.
version: 3.2.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_timezone: ^5.0.0
  device_calendar:
    path: ../
  collection: ^1.19.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true